wrap fields in arc and clone it in open_outbound
Fixes:

```
error[E0759]: `self` has an anonymous lifetime `'_` but it needs to
satisfy a `'static` lifetime requirement
```