Implement StreamMuxer trait for Connection (#2)
* start impl StreamMuxer trait

* implement poll_outbound fn

* implement poll fns

* impl close and flush_all fns

* wrap fields in arc and clone it in open_outbound

Fixes:

```
error[E0759]: `self` has an anonymous lifetime `'_` but it needs to
satisfy a `'static` lifetime requirement
```

* implement poll_event fn

* add some comments

* close `incoming_data_channels_rx` in close

to prevent adding new data channels

* add comment to destroy_outbound

* drop locks early

* reduce the number of locks

* bring back noise and start smoke tests

* reserve 1 for the initial substream

* smoke tests: add webrtc fingerprint to dialing addr

* use tokio executor in swarm

* do not assume fingerprint to be last

actually it's supposed to be 3rd (ip, port, fingerprint, peer_id)
but let's not assume anything

* increase read buf size to 8192

and reduce one in smoke tests

* verify peer_id and close initial stream (used for noise)

* allow changing read buf cap in Connection

* use Default::default when constructing RTCDataChannelInit

* remove unnecessary field from RTCDataChannelInit

* remove next_outbound_channel_id

It turned out we actually don't need it. webrtc-rs lib will increase
channel ID for us (on both ends on the connection).

Also, extract `register_data_channel_open_handler` fn to reduce the
amount of duplicated code.

* fix some clippy warnings

* exchange TLS fingerprint certificates inside noise

Fixes
https://github.com/melekes/libp2p-webrtc-direct/pull/2#discussion_r889028845

* remove udp_mux files and update PollDataChannel

based on new ice, sctp and data crates

* include old code